### ISSUE TITLE
UIPanGestureRecognizer does not fire State.Ended

### ISSUE THREAD

**Issue by adipascu** [sephiroth74/AndroidUIGestureRecognizer#3]
Is it currently working as intended ?

**Comment by sephiroth74** [comment]
Yeah it should. do you have a sample code to test?

**Comment by adipascu** [comment]
Thank you for the fast update, I am creating a sample right now.

**Comment by adipascu** [comment]
Here is a sample project to test.

https://github.com/adi1133/GestureRecognizerIssue

Steps to reproduce the issue:

- Build/Install/Run
- Drag one finger over the content of the activity
- Check out text view
- Check out log cat

**State.Ended** is never fired.

**Comment by sephiroth74** [comment]
I'll take a look as soon as I can.

**Comment by adipascu** [comment]
I fixed it im my fork, I will post a PR soon.

**Comment by adipascu** [comment]
Thank you for fixing this !

**Comment by sephiroth74** [comment]
thank you for the feedback!
