### ISSUE TITLE
UISwipeGestureRecognizer detects swipes without lifting the finger.

### ISSUE THREAD

**Issue by adipascu** [sephiroth74/AndroidUIGestureRecognizer#7]
UISwipeGestureRecognizer generates Ended action when finger is not lifted up.
Is this working as intended ?

**Comment by sephiroth74** [comment]
yes, this is the intended behavior (it is not what I thought too, but this is how it is implemented in the ios framework)

**Comment by adipascu** [comment]
I have created a custom gesture recognizer that fixes this issue, if there is interest I can talk with my team to upstream it.
